#importing the numpy library from python as np

In [1]:
#importing the numpy library from python as np
import numpy as np

a= np.array([100,102,103,309])
a

array([100, 102, 103, 309])

#returning the elements of the tuple

In [27]:
#returning the number of elements 
print(a.shape)


(4,)


1 dimensional array

In [7]:
#1 dim array
arr = np.array([1,2,4])
print(arr)

[1 2 4]


2 dimensional array

In [28]:
b= np.array(
    [[1,2,3],
    [4,5,6],
    [7,8,9]]
)

#indexing the multidimensional aray
b[1,1]= 10

print(b)

# to show the dimension of the array
b.ndim

b.shape

[[ 1  2  3]
 [ 4 10  6]
 [ 7  8  9]]


(3, 3)

3 dimensional array

In [29]:
#3 dimensional array

c= np.array([
    [
        [1,2,3,],
        [1,2,3],
        [1,2,3]
    ],
    [
        [1,2,3],
        [1,2,3],
        [1,2,3]
    ],
    [
        [1,2,3],
        [1,2,3],
        [1,2,3]
    ]
])
c.ndim

c[2,2,2] = 10
print(c)

np.empty((2,3,1))

c.shape


[[[ 1  2  3]
  [ 1  2  3]
  [ 1  2  3]]

 [[ 1  2  3]
  [ 1  2  3]
  [ 1  2  3]]

 [[ 1  2  3]
  [ 1  2  3]
  [ 1  2 10]]]


(3, 3, 3)

complex data type

In [31]:
np.array([0,4,-4], dtype=complex)

array([ 0.+0.j,  4.+0.j, -4.+0.j])

In [30]:

arr = np.array([[[[1,3,4,5]]]])

print(arr.ndim)

arr[0,0,0,0] = 10

print(arr)

4
[[[[10  3  4  5]]]]


In [33]:
#creating the random array

np.empty((2,3,4))

array([[[1.12746729e-311, 7.65801751e-322, 0.00000000e+000,
         0.00000000e+000],
        [1.89146896e-307, 1.16095484e-028, 1.96088859e+243,
         9.44416446e-096],
        [1.12958007e+277, 2.21211602e+214, 1.96099265e+243,
         9.16526748e+242]],

       [[1.21362457e+132, 1.00854119e+141, 4.11083805e+223,
         9.15279752e+242],
        [9.24080564e+135, 9.48149670e-076, 8.70781396e-153,
         4.11083811e+223],
        [9.15279752e+242, 8.93168689e+271, 4.98131536e+151,
         1.94920670e-153]]])

In [39]:
#creating empty matrix

# with 0


y = np.zeros((2,2))
y

# with 1

y = np.ones_like(y)
y

array([[1., 1.],
       [1., 1.]])

In [40]:
list(range(7))

[0, 1, 2, 3, 4, 5, 6]

In [7]:
#linespace
#(Start,stop,Evenspaced)
x = np.linspace(1,5,5)
x-1

array([0., 1., 2., 3., 4.])

Martix addition
Element wise nuktioication

In [17]:
a= np.array(((1,2),(3,4)))
b=a+1
a
b
a+b
a*b

array([[ 2,  6],
       [12, 20]])

 Matrix multiplication

In [18]:
b=a.T
np.matmul(a,b)

array([[ 5, 11],
       [11, 25]])